openapi: 3.1.0
info:
  title: Asgardeo AI Management Agent (Context Aware)
  description: API using context variables for request data.
  version: 0.3.0
servers:
  # You can add server URLs here if desired, e.g.:
  # - url: http://localhost:8000
  #   description: Local development server
  # - url: https://your-deployed-agent.choreoapps.dev
  #   description: Production server
  - url: / # Default relative URL
paths:
  /chat:
    post:
      tags:
        - Chat
      summary: Handle Chat Interaction
      description: >
        Handles chat requests, setting API key and Org Name in context variables
        internally to interact with the Asgardeo management agent.
      operationId: chat_endpoint_chat_post
      parameters:
        - name: api-key # Matches alias='api-key'
          in: header
          required: true
          description: Base64 encoded 'clientId:Secret' for Asgardeo authentication.
          schema:
            type: string
            format: base64
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ChatRequest'
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ChatResponse'
        '400':
          description: Bad Request (e.g., Invalid Payload, Missing Org Name)
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPError'
        '401':
          description: Unauthorized (e.g., Missing or Invalid API Key)
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPError'
        '422':
          description: Validation Error (FastAPI specific)
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPError'
  /health:
    get:
      tags:
        - Health
      summary: Health Check
      description: Simple health check endpoint.
      operationId: health_check_health_get
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: ok
                  target:
                    type: string
                    example: Asgardeo Agent (Context Aware)

components:
  schemas:
    ChatMessage:
      type: object
      required:
        - role
        - content
      properties:
        role:
          type: string
          pattern: "^(user|agent)$"
          description: The role of the message sender ('user' or 'agent').
        content:
          type: string
          description: The text content of the message.
      title: ChatMessage
      description: Represents a single message turn in the chat.

    ChatRequest:
      type: object
      required:
        - organization_name
        - chat
      properties:
        organization_name:
          type: string
          description: The target Asgardeo organization name.
        chat:
          type: array
          items:
            $ref: '#/components/schemas/ChatMessage'
          minItems: 1 # Must have at least one message
          description: >-
            List of chat messages representing the conversation history, ending
            with the latest user message.
      title: ChatRequest
      description: Request payload for the /chat endpoint.

    ChatResponse:
      type: object
      required:
        - role
        - content
      properties:
        role:
          type: string
          default: agent
          description: The role of the message sender (always 'agent' for response).
        content:
          type: string
          description: The agent's response message content.
      title: ChatResponse
      description: Response payload for the /chat endpoint.

    # Generic Error Schema
    HTTPError:
      type: object
      properties:
        detail:
          type: string
          description: Error detail message.
      title: HTTPError

    # FastAPI Specific Validation Error Schema
    ValidationError:
      type: object
      required:
        - loc
        - msg
        - type
      properties:
        loc:
          type: array
          items:
            anyOf:
              - type: string
              - type: integer
          title: Location
        msg:
          type: string
          title: Message
        type:
          type: string
          title: Error Type
      title: ValidationError

    HTTPValidationError:
      type: object
      properties:
        detail:
          type: array
          items:
            $ref: '#/components/schemas/ValidationError'
          title: Detail
      title: HTTPValidationError
